# -*- coding: utf-8 -*-
"""major_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBfWlNR8L4Djp3aiI8ThF_PAl5J6jRGm
"""

import pandas as pd
import numpy as np
import random

infectious_map = {
    "flu": ["fever","cough","fatigue","headache"],
    "covid-19": ["fever","cough","fatigue","difficulty_breathing"],
    "dengue": ["fever","fatigue","rash","body_pain","platelet_low"],
    "malaria": ["fever","fatigue","body_pain"],
    "typhoid": ["fever","fatigue","vomiting","headache"],
    "pneumonia": ["fever","cough","difficulty_breathing","chest_pain"],
    "tuberculosis": ["cough","fatigue","fever"],
    "uti": ["fever","fatigue"],
    "gastroenteritis": ["vomiting","fatigue"],
    "hepatitis": ["fatigue","vomiting"],
    "chickenpox": ["fever","rash"],
    "measles": ["fever","rash","cough"],
    "cholera": ["vomiting","fatigue"],
    "meningitis": ["fever","headache","vomiting"],
    "sepsis": ["fever","fatigue","wbc_abnormal"]
}

respiratory_map = {
    "asthma": ["cough","difficulty_breathing","chest_pain"],
    "copd": ["cough","difficulty_breathing"],
    "bronchitis": ["cough","fatigue","difficulty_breathing"],
    "sinusitis": ["headache","cough"]
}

chronic_map = {
    "diabetes": ["fatigue"],
    "hypertension": ["headache"],
    "ckd": ["fatigue"],
    "obesity": ["fatigue"]
}

neuro_map = {
    "migraine": ["headache","vomiting"],
    "epilepsy": ["fatigue"],
    "depression": ["fatigue"],
    "anxiety": ["fatigue"]
}

critical_map = {
    "heart failure": ["chest_pain","fatigue"],
    "stroke": ["fatigue"],
    "appendicitis": ["vomiting","body_pain"],
    "pancreatitis": ["vomiting","body_pain"],
    "peptic ulcer": ["chest_pain"],
    "arthritis": ["body_pain"],
    "rheumatoid arthritis": ["body_pain"],
    "lupus": ["fatigue","rash"],
    "anemia": ["fatigue"],
    "hypothyroidism": ["fatigue"],
    "allergy": ["rash","cough"],
    "jaundice": ["fatigue"],
    "leukemia": ["fatigue","wbc_abnormal"]
}

disease_feature_map = {
    **infectious_map,
    **respiratory_map,
    **chronic_map,
    **neuro_map,
    **critical_map
}

df = pd.read_csv('/content/master_diagnostic.csv')
df.head()

df.drop_duplicates(inplace=True)
df.fillna(0, inplace=True)

df['disease'] = df['disease'].str.lower().str.strip()

df.drop(columns=[
    'risk_factor_count',
    'composite_risk_score',
    'severity_index',
    'duration_score',
    'age_severity_interaction',
    'symptom_risk_interaction'
], errors='ignore', inplace=True)

symptoms = [
    'fever','cough','fatigue','difficulty_breathing',
    'headache','vomiting','chest_pain','body_pain','rash'
]

for col in symptoms:
    df[col] = 0

df['platelet_low'] = 0
df['wbc_abnormal'] = 0

for i, row in df.iterrows():
    disease = row['disease']

    if disease in disease_feature_map:
        for feature in disease_feature_map[disease]:
            if feature in df.columns:
                df.at[i, feature] = 1 if random.random() > 0.2 else 0

df.head()

for i, row in df.iterrows():
    if row['disease'] == 'dengue':
        df.at[i,'platelet_low'] = 1

    if row['disease'] in infectious_map:
        df.at[i,'wbc_abnormal'] = 1

df['symptom_count'] = df[symptoms].sum(axis=1)

df['risk_score'] = df[['blood_pressure','cholesterol']].sum(axis=1)

df['severity_duration_interaction'] = df['severity'] * df['duration']

df.to_csv('/content/model_ready.csv', index=False)

df.head(500)

# =========================
# 1. IMPORT LIBRARIES
# =========================
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# =========================
# 2. LOAD FINAL DATASET
# =========================
df = pd.read_csv('/content/model_ready.csv')

print("Dataset Shape:", df.shape)

# =========================
# 3. DEFINE FEATURES & TARGET
# =========================
X = df.drop(columns=['disease', 'risk_factor_list'], errors='ignore') # Drop 'risk_factor_list' as it contains non-numeric strings
y = df['disease']

# =========================
# 4. TRAIN-TEST SPLIT
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y   # IMPORTANT for multi-class balance
)

# =========================
# 5. TRAIN RANDOM FOREST
# =========================
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42
)

rf_model.fit(X_train, y_train)

# =========================
# 6. PREDICTIONS
# =========================
y_pred = rf_model.predict(X_test)

# =========================
# 7. EVALUATION
# =========================
print("\nAccuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n", classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

for col in df.columns:
    if df[col].dtype == 'object':
        print("String column found:", col)

df.drop(columns=['risk_factor_list'], inplace=True)

X = df.drop(columns=['disease'])
y = df['disease']
print(X.dtypes)

!pip install xgboost

df.drop(columns=['risk_factor_list'], inplace=True, errors='ignore')

for col in df.columns:
    if df[col].dtype == 'object':
        print("Still string column:", col)

X = df.drop(columns=['disease', 'disease_encoded'])
y = df['disease_encoded']
print(X.dtypes)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
from xgboost import XGBClassifier

df = pd.read_csv('/content/model_ready.csv')

le = LabelEncoder()
df['disease_encoded'] = le.fit_transform(df['disease'])

X = df.drop(columns=['disease', 'disease_encoded', 'risk_factor_list'], errors='ignore') # Drop 'risk_factor_list' here as it's an object type
y = df['disease_encoded']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


xgb_model = XGBClassifier(
    objective='multi:softprob',   # for probabilities
    num_class=len(le.classes_),
    n_estimators=150,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb_model.fit(X_train, y_train)


y_pred = xgb_model.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n",
      classification_report(y_test, y_pred, target_names=le.classes_))

import numpy as np

probs = xgb_model.predict_proba(X_test)

top_3 = np.argsort(probs, axis=1)[:, -3:]

for i in range(5):
    print("\nPatient", i+1)
    for idx in reversed(top_3[i]):
        print(le.classes_[idx], "→", round(probs[i][idx]*100, 2), "%")

from sklearn.ensemble import VotingClassifier

ensemble_model = VotingClassifier(
    estimators=[
        ('rf', rf_model),
        ('xgb', xgb_model)
    ],
    voting='soft'   # IMPORTANT → uses probabilities
)

ensemble_model.fit(X_train, y_train)

# Predictions
y_pred_ens = ensemble_model.predict(X_test)

# Evaluation
from sklearn.metrics import accuracy_score, classification_report

print("Ensemble Accuracy:", accuracy_score(y_test, y_pred_ens))

print("\nClassification Report:\n",
      classification_report(y_test, y_pred_ens, target_names=le.classes_))

import numpy as np

probs = ensemble_model.predict_proba(X_test)

top_3 = np.argsort(probs, axis=1)[:, -3:]

for i in range(5):
    print("\nPatient", i+1)
    for idx in reversed(top_3[i]):
        print(le.classes_[idx], "→", round(probs[i][idx]*100, 2), "%")

import joblib

joblib.dump(ensemble_model, 'disease_model.pkl')
joblib.dump(le, 'label_encoder.pkl')

print("✅ Model Saved")

import joblib

model = joblib.load('disease_model.pkl')
le = joblib.load('label_encoder.pkl')

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/model_ready.csv')

# Drop the 'risk_factor_list' column if it exists
if 'risk_factor_list' in df.columns:
    df.drop(columns=['risk_factor_list'], inplace=True)
    print("Successfully dropped 'risk_factor_list' column.")
else:
    print("'risk_factor_list' column not found in the DataFrame.")

# Save the modified DataFrame back to the CSV file
df.to_csv('/content/model_ready.csv', index=False)
print("Updated 'model_ready.csv' saved.")

df.head(10)

